### ISSUE TITLE
getIp() - unexpected result for non-192.168.-networks

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/ces-commons#1]
When calling `getIp()` in an environment that does not have a network adapter that has a `192.168.x.x`  IP address, the IP address of the first network adapter (`eth0`) is returned.

In case of the ecoystem `eth0` is the NAT adapter that cannot be reached from outside of the VM. It  usually has the address `10.0.2.15`.

Please make the logic more robust so it also returns the externally accessible IP address (private or public network instead of the NAT adapter) even when this IP address does not start in `192.168.`.

The behaviour can be reproduced by starting an [ecosystem with a private network](https://github.com/cloudogu/ecosystem/blob/a4fdfb4b0390a21e901c0ef0a651b31f02654729/Vagrantfile#L19) and an IP address of for example `192.170.2.42`.  
When calling `vagrant up`, it will output a setup link for `http://10.0.2.15:8080`, whereas it can only be reached at  `http://192.170.2.42:8080`.

A workaround would be to query the external IP address via `vagrant ssh -c "ifconfig eth1"` and to perform a setup. However, when shutting down the ecosystem and starting it again with a different IP (which is not unlikely for public/bridged networks), the ecosystem will no longer be accessible from outside the VM.

You can reproduce this like so:

* Start the ecosystem VM, for example as shown above with an IP of `192.170.2.42`.
* Perform a minimal CES setup
* When everything is done, shut down the VM, e.g. with `vagrant halt`.
* Change the IP address in the `Vagrantfile`, e.g. `182.180.3.23`.
* Start the VM again, `vagrant up`
* Access the ecosystem in browser via `https://182.180.3.23`.

Right now, the last step does not return an answer. Desired behaviour is that we can reach the ecosystem at the new address.

**Comment by robertauer** [comment]
Remember to set correct get_type() and get_ip() functions either in functions.sh or install/setup-message.sh of the ecosystem.

**Comment by robertauer** [comment]
Remember merging https://github.com/cloudogu/etcd/tree/feature/ces_commons_issue_1 and https://github.com/cloudogu/ecosystem/tree/feature/ces_commons_issue_1 branches to fix this issue.
