### ISSUE TITLE
Install issues of new ces-commons

### ISSUE THREAD

**Issue by mbehlendorf** [cloudogu/ces-commons#11]
When upgrading ces-commons versions lower than 0.1.4, the postinst-script is failing because systemd wants to set an already installed symlink when enabling ipchangecheck unit.
```
Failed to execute operation: File exists
dpkg: error processing package ces-commons (--configure):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
ces-commons
```

**Comment by ppxl** [comment]
This issue seems to be fixed by #12. Closing the issue.
